/**
 * 扩展接入
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject4 model module.
 * @module model/InlineObject4
 * @version 1.0.0
 */
class InlineObject4 {
    /**
     * @member {String} phone
     * @type {String}
     */
    phone;
    /**
     * @member {String} code
     * @type {String}
     */
    code;
    /**
     * @member {String} robotcode
     * @type {String}
     */
    robotcode;
    /**
     * @member {String} robotcodeid
     * @type {String}
     */
    robotcodeid;

    

    /**
     * Constructs a new <code>InlineObject4</code>.
     * @alias module:model/InlineObject4
     * @param phone {String} 国内手机号
     * @param code {String} 
     * @param robotcode {String} 
     * @param robotcodeid {String} 
     */
    constructor(phone, code, robotcode, robotcodeid) { 
        
        InlineObject4.initialize(this, phone, code, robotcode, robotcodeid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phone, code, robotcode, robotcodeid) { 
        obj['phone'] = phone;
        obj['code'] = code;
        obj['robotcode'] = robotcode;
        obj['robotcodeid'] = robotcodeid;
    }

    /**
     * Constructs a <code>InlineObject4</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject4} obj Optional instance to populate.
     * @return {module:model/InlineObject4} The populated <code>InlineObject4</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject4();

            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('robotcode')) {
                obj['robotcode'] = ApiClient.convertToType(data['robotcode'], 'String');
            }
            if (data.hasOwnProperty('robotcodeid')) {
                obj['robotcodeid'] = ApiClient.convertToType(data['robotcodeid'], 'String');
            }
        }
        return obj;
    }
}



export default InlineObject4;

