/**
 * 扩展接入
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

// CommonJS-like environments that support module.exports, like Node.
factory(require('expect.js'), require(process.cwd()+'/src/index'));

'use strict';

var instance;

beforeEach(function() {
  instance = new OpenapiJsClient.DefaultApi();
});

var getProperty = function(object, getter, property) {
  // Use getter method if present; otherwise, get the property directly.
  if (typeof object[getter] === 'function')
    return object[getter]();
  else
    return object[property];
}

var setProperty = function(object, setter, property, value) {
  // Use setter method if present; otherwise, set the property directly.
  if (typeof object[setter] === 'function')
    object[setter](value);
  else
    object[property] = value;
}

describe('DefaultApi', function() {
    describe('friendLoginPost', function() {
      it('should call friendLoginPost successfully', function(done) {
        //uncomment below and update the code to test friendLoginPost
        //instance.friendLoginPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('juguguGetPhoneCodePost', function() {
      it('should call juguguGetPhoneCodePost successfully', function(done) {
        //uncomment below and update the code to test juguguGetPhoneCodePost
        //instance.juguguGetPhoneCodePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('jugugugGetReleaseNFT1155PNGCodePost', function() {
      it('should call jugugugGetReleaseNFT1155PNGCodePost successfully', function(done) {
        //uncomment below and update the code to test jugugugGetReleaseNFT1155PNGCodePost
        //instance.jugugugGetReleaseNFT1155PNGCodePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('transferNFTPost', function() {
      it('should call transferNFTPost successfully', function(done) {
        //uncomment below and update the code to test transferNFTPost
        //instance.transferNFTPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userNFTsPost', function() {
      it('should call userNFTsPost successfully', function(done) {
        //uncomment below and update the code to test userNFTsPost
        //instance.userNFTsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
});